### ISSUE TITLE
Trying to get terraform required_version fails

### ISSUE THREAD

**Issue by thomaschaaf** [magodo/hclgrep#1]
I'm trying to read the terraform.required_version but I am unable to get a match.

```hcl
terraform {
  required_version = "1.3.5"
}
```

I tried `hclgrep -x 'terraform.required_version' main.tf` but that did not work.

**Comment by magodo** [comment]
@thomaschaaf This is not how `hclgrep` works. Instead, you shall do:

```shell
hclgrep -x 'terraform {@*_}' -x 'required_version = $ver' -w ver main.tf
"1.3.5"
```
